### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by 17nak1** [chm-diederichs/sha3-wasm#1]
I have tried the provided examples but got an error "Memory access out of bounds" when calling Keccak.keccak224() (or other options). 
Is there any solution to fix this error?

**Comment by chm-diederichs** [comment]
Hmm ok, tests seem to be passing.
Are you using this in browser or with node?
Does the error comes when calling .keccak224() or .update()?

**Comment by 17nak1** [comment]
I am using this on node and calling  .keccak224() gives the error.
Start running the test.js gives me the same error. It seems it comes from sha3-wasm/index.js:75:16.

**Comment by chm-diederichs** [comment]
Ok, I can't reproduce this, but try installing v0.0.7 and see if that works

**Comment by chm-diederichs** [comment]
Hey, did you manage to try this out? Haven't been able to reproduce so, if you could let me know if this patched it that would be awesome. Thanks!

**Comment by chm-diederichs** [comment]
@17nak1 before i close this issue, did you manage to try this fix or did you switch to another module?

**Comment by 17nak1** [comment]
Unfortunately, I couldn't use it and switched to another module.

**Comment by chm-diederichs** [comment]
Ahh ok, sorry I couldn't patch that for you. Thanks for your feedback, I hope the project went well
